export type GaleriaDetention = 'busted' | 'pretrial' | 'investig' | 'loose' | 'wanted';
export type GaleriaHair = 'short' | 'bald' | 'wave' | 'cap' | 'slick';

export interface PersonCaseItem {
  title: string;
  description: string;
  estimatedDamage?: string;
  crimeTypes: string[];
  sourceUrl?: string;
  sourceLabel?: string;
}

export interface GaleriaEntry {
  id: string;
  name: string;
  subtitle: string;
  description: string;
  detention: GaleriaDetention;
  detentionLabel: string;
  crimes: string[];
  amountLabel: string;
  amount: string;
  // Mugshot params
  variant?: number;
  glasses?: boolean;
  hair?: GaleriaHair;
  // Photo (user-provided URL) + credit
  photoUrl?: string;
  photoCredit?: string;
  // Detail page data
  videoId?: string;
  videoChannel?: string;
  videoTitle?: string;
  videoSummary?: string;
  newsTag?: string;
  newsKeywords?: string[];
  personCases?: PersonCaseItem[];
}

export const GALERIA: GaleriaEntry[] = [
  {
    id: 'orban-viktor',
    name: 'Orbán Viktor',
    subtitle: 'Volt miniszterelnök',
    description: '16 éves kormányzás alatt épített ki rendszert, amelyben állami vagyon és közpénzek politikailag közelálló vállalkozókhoz áramlottak. Az aranykonvoj-ügyben ügyvéd benyújtott feljelentés terrorcselekmény gyanúját is felveti. A Hatvanpuszta-majorság forrása máig megmagyarázatlan.',
    detention: 'investig',
    detentionLabel: 'Feljelentés benyújtva',
    crimes: ['Hűtlen kezelés', 'Közpénzek elherdálása', 'Befolyással visszaélés'],
    amountLabel: 'Becsült közpénzérintettség',
    amount: 'Több ezer milliárd Ft',
    variant: 2, glasses: false, hair: 'slick',
    photoUrl: '/images/persons/orban.jpg',
    photoCredit: 'Orbán Viktor Facebook oldala',
    videoId: 'HiW9r1M32ug',
    videoChannel: '444.hu',
    videoTitle: 'Hatvanpuszta — Orbán titkos majorja',
    videoSummary: 'Drónfelvételek és helyszíni riport mutatja meg, hogyan fejlődött az elmúlt években az a 250 hektáros major, amelynek valódi tulajdonosa és finanszírozási forrása máig ismeretlen — és amelynek értéke összeegyeztethetetlen Orbán nyilvánosan bejelentett vagyonával.',
    newsTag: 'orbán',
    newsKeywords: ['orbán viktor', 'orbán', 'hatvanpuszta', 'aranykonvoj', 'zsigmond ágost', 'nemzeti múzeum'],
    personCases: [
      {
        title: 'Hatvanpuszta',
        description: 'A 250 hektáros, ~20 milliárd forintra becsült majorság hivatalosan nem Orbán Viktoré, hanem édesapja, Orbán Győző nevén van — Orbán mindmáig tagadja, hogy a major az övé lenne, mégis ő lakja és kezelteti. A finanszírozási forrás és a tényleges haszonélvező ismeretlen; az ingatlan értéke összeegyeztethetetlen a nyilvánosan bejelentett vagyonával. 2025-ben Hadházy Ákos feljelentést tett, mert a majoron műemlék jellegű épületet bontottak le engedély nélkül — az ügyészség nyomozást indított.',
        estimatedDamage: '~20 milliárd Ft (ingatlanérték)',
        crimeTypes: ['Vagyonnyilatkozat megsértése', 'Megmagyarázatlan vagyonosodás', 'Stróman-tulajdon (gyanú)', 'Engedély nélküli műemlékbontás'],
        sourceUrl: 'https://telex.hu/belfold/2025/10/12/hadhazy-akos-hatvanpuszta-ugyeszseg-muemlek',
        sourceLabel: 'Telex',
      },
      {
        title: 'Aranykonvoj-ügy',
        description: '2026 tavaszán a NAV és a titkosszolgálat megakadályozott egy Ukrajna határán átkelő konvojt, amely aranyat és devizát szállított Orbán-közelből. Az ügyvéd feljelentésben terrorcselekmény-gyanú is szerepel.',
        estimatedDamage: 'Ismeretlen (arany + deviza)',
        crimeTypes: ['Pénzmosás', 'Terrorcselekmény (gyanú)', 'Csempészet'],
        sourceUrl: 'https://444.hu/2026/06/14/egy-nav-os-belso-jelentes-szerint-torvenysertoen-jarhatott-el-a-legfobb-ugyeszseg-az-aranykonvoj-ugyben',
        sourceLabel: '444',
      },
      {
        title: 'NER rendszer kiépítése',
        description: 'A Nemzeti Együttműködés Rendszere keretében szisztematikusan kerültek az állami megrendelések Orbán-közeliekhez — Mészáros, Tiborcz, Balásy és más oligarchák cégeihez — közbeszerzési verseny mellőzésével.',
        estimatedDamage: 'Több ezer milliárd Ft (teljes rendszer)',
        crimeTypes: ['Közbeszerzési visszaélés', 'Összeférhetetlenség', 'Közhatalommal visszaélés'],
        sourceUrl: 'https://telex.hu/g7/penz/2026/06/16/ner-vagyon-leggazdagabb-magyarok',
        sourceLabel: 'Telex / G7',
      },
      {
        title: 'Nemzeti Múzeum műkincs-elajándékozás',
        description: 'A Válasz Online 2026 májusában tárta fel, hogy az Orbán-kormány Zsigmond Ágost lengyel király diszpáncélját — a Nemzeti Múzeum egyik legritkább középkori darabját — elajándékozta Lengyelországnak. Az átadás mögött NER-diplomáciai érdekek állnak; a döntés a köz megkérdezése és parlamenti jóváhagyás nélkül született.',
        estimatedDamage: '1,53 milliárd Ft',
        crimeTypes: ['Nemzeti örökség elherdálása', 'Közvagyon elajándékozása', 'Átláthatóság megsértése'],
        sourceUrl: 'https://www.valaszonline.hu/2026/05/15/zsigmond-agost-diszpancelja-elajandekozas-nemzeti-muzeum-mutargyak-ner-lengyelorszag/',
        sourceLabel: 'Válasz Online',
      },
      {
        title: 'TAO pénzek – Puskás Akadémia és futballbirodalom',
        description: 'A 2011-ben bevezetett vállalati adókedvezmény (TAO) keretében 2011–2021 között 1107 milliárd forint áramlott sportolók helyett döntően Fidesz-közeli stadion- és akadémia-projektekhez. Orbán Viktor saját alapítású Puskás Akadémiája (Felcsút) az egyik legnagyobb haszonélvező; a Transparency International rendszeres korrupciós kockázatot állapított meg, és a kedvezményezetti hálózat átfedett az Orbán-közeli üzleti körökkel.',
        estimatedDamage: '1107 milliárd Ft (2011–2021, teljes TAO-keret)',
        crimeTypes: ['Közhatalommal visszaélés', 'Közpénz magáncélra fordítása', 'Összeférhetetlenség'],
        sourceUrl: 'https://adatbazis.k-monitor.hu/adatbazis/cimkek/tao-penzek',
        sourceLabel: 'K-Monitor',
      },
      {
        title: 'Paks II. – titkos szerződés Putyinnal',
        description: '2014 januárjában Orbán Viktor Moszkvában, előzetes parlamenti felhatalmazás és nyilvános vita nélkül, személyesen írta alá a Paks II. reaktor-bővítés szerződését Vlagyimir Putyinnal. Egy titkos záradék 2045-ig zárolta az összes pénzügyi részletet. Az EU Bírósága 2025 szeptemberében jogellenesnek ítélte az állami támogatást; az építkezést mégis folytatják.',
        estimatedDamage: '~3 ezer milliárd Ft (projekt) · ~80 Mrd Ft hűtlen kezelés (Tordai-feljelentés)',
        crimeTypes: ['Átláthatóság megsértése', 'EU-szabályok megsértése', 'Parlamenti kontroll kijátszása'],
        sourceUrl: 'https://444.hu/2015/01/14/paks-evforulo-2014-2015-orban-putyin-moszkva-kreml-atomeromu-energetika/',
        sourceLabel: '444',
      },
      {
        title: 'Honvédségi gépek kormányzati használata',
        description: 'Magyar katonai repülőgépek rendszeresen szállítják Orbán Viktort magáncélú utazásokra is. 2025-ben kiszivárgott, hogy Orbán egy Kairó–Olaszország útvonalon magáncélból tért el — az Átlátszó szerint az előző nap egy olasz éttermi fotón tűnt fel a családjával. Visszafizetett 2+ millió forintot a repülőjegyért; a repülési adatokat 30 éves titoktartással kezelik.',
        crimeTypes: ['Közpénz magáncélra fordítása', 'Átláthatóság megsértése', 'Titoktartási visszaélés'],
        sourceUrl: 'https://atlatszo.hu/kozpenz/2022/09/21/itt-a-szerzodes/',
        sourceLabel: 'Átlátszó',
      },
      {
        title: 'Pharaon-ügy',
        description: '2016 őszén kiderült, hogy Ghaith Pharaon — szaúdi üzletember, akit az FBI 25 éve körözött pénzmosás és terrorizmus finanszírozásának gyanúja miatt — ingatlant vásárolt Orbán Viktor felcsúti rezidenciájának szomszédságában. A kormány bagatellizálta a körözött személy szomszédságát; az USA nagykövete nyilvánosan cáfolta a kormány állítását. Pharaon 2017 januárjában Bejrútban elhunyt.',
        crimeTypes: ['Biztonsági kockázat elhallgatása', 'Titkosszolgálati mulasztás (gyanú)', 'Szuspekt kapcsolatok'],
        sourceUrl: 'https://magyarnarancs.hu/belpol/a-szaudi-szomszed-101257',
        sourceLabel: 'Magyar Narancs',
      },
      {
        title: 'Orbán szőlők – rezidencia és megmagyarázatlan vagyonosodás',
        description: 'Az Orbán-féle felcsúti ingatlanegyüttes (majorság, szőlők, melléképületek) tényleges tulajdonosa és finanszírozási forrása ismeretlen — a terület értéke és beruházásai összeegyeztethetetlenek Orbán Viktor nyilvánosságra hozott vagyonával. A K-Monitor „Orbán szőlők" adatbázisában összegyűlt sajtónyomozások ennek az ingatlan-terjeszkedésnek a rekonstruálását kísérlik meg.',
        crimeTypes: ['Megmagyarázatlan vagyonosodás', 'Vagyonnyilatkozat teljessége', 'Stróman-tulajdon (gyanú)'],
        sourceUrl: 'https://adatbazis.k-monitor.hu/adatbazis/cimkek/orban-viktor/orban-szolok',
        sourceLabel: 'K-Monitor',
      },
      {
        title: 'MNB alapítványok – miniszterelnöki felelősség',
        description: 'Matolcsy Györgyöt Orbán Viktor nevezte ki MNB-elnöknek 2013-ban, és az alapítványokba átutalt 266+ milliárd forintnyi közpénzről az Orbán-kormány tudott. Az ÁSZ 2025-ben büntetőfeljelentést tett; sajtójelentések szerint Orbán és Matolcsy között megállapodás születhetett a felelősség alóli mentesítésről. A miniszterelnöki felügyelet és az MNB-függetlenség jogi határa maga is vitatott.',
        crimeTypes: ['Felügyeleti mulasztás', 'Felelősség elhárítása', 'Közhatalommal visszaélés'],
        sourceUrl: 'https://telex.hu/gazdasag/2026/06/11/matolcsy-gyorgy-170-millio-szabadsag-magyar-nemzeti-bank-vizsgalat',
        sourceLabel: 'Telex',
      },
    ],
  },
  {
    id: 'rogan-antal',
    name: 'Rogán Antal',
    subtitle: 'Volt kabinetirodát vezető miniszter',
    description: 'A letelepedési kötvény-botrány kulcsfigurája: Rogán Antal belügyminiszteri szerepkörében felügyelte azt a programot, amelyen keresztül kb. 7 000 tartózkodási engedély kelt el egyenként 300 000 euróért — a kezelési díjak és jutalékok Rogán-közeli offshore hálózatokba folytak. Az USA OFAC 2024-ben szankciókat vetett ki rá korrupcióval és demokratikus intézmények aláásásával összefüggésben.',
    detention: 'investig',
    detentionLabel: 'OFAC szankció · vizsgálat',
    crimes: ['Letelepedési kötvény botrány', 'OFAC szankció', 'Befolyással visszaélés'],
    amountLabel: 'Becsült érintett összeg',
    amount: 'Több száz milliárd Ft',
    variant: 0, glasses: false, hair: 'short',
    photoUrl: 'https://image.blikk.hu/1/S9Ck9kpTURBXy81ZjE4ZDcwZjI3M2FmYzE0ZjY1YWZkNmNkZDk5ODA1Ny5qcGeTlQMAO80Ra80JzJMJpmY2OGQ5MAaTBc0DMM0CZN4AAaEwBQ/rogan-antal-megszolalt-a-valasztasok-utan-foto-korponai-tamas',
    photoCredit: 'Blikk / Korponai Tamás',
    videoId: 'ePRovUEGY1c',
    videoChannel: 'Juhász Péter | Juhi',
    videoTitle: 'Rogán és a letelepedési kötvény',
    videoSummary: 'A NER 100 sorozat Rogán Antal hatalmának forrásait térképezi fel. A letelepedési kötvényprogram több száz millió eurós forgalmat generált, és Rogán neve rendszeresen felbukkan a közelében — de pontosan mit tudunk bizonyítani?',
    newsTag: 'rogán',
    newsKeywords: ['rogán antal', 'rogán', 'letelepedési kötvény'],
    personCases: [
      {
        title: 'Letelepedési kötvény-botrány',
        description: 'A 2012–2017 között működő program keretében Magyarország tartózkodási engedélyeket értékesített főleg kínai és közel-keleti befektetőknek, egyenként 300 000 euróért. A kötvények kibocsátását és értékesítését irányító offshore cégek (köztük a Discus Holdings és az Arton Capital) Rogán-közeli hálózatokhoz köthetők. A program 2,1 milliárd eurós forgalmat bonyolított, miközben az átvilágítás minimális volt — az OLAF és több külföldi hatóság is vizsgálta.',
        estimatedDamage: '~2,1 milliárd EUR (teljes programforgalom)',
        crimeTypes: ['Korrupció', 'Pénzmosás', 'Befolyással visszaélés', 'Átláthatóság megsértése'],
        sourceUrl: 'https://444.hu/2018/10/08/30-milliard-forintot-buktak-a-magyar-emberek-a-rogan-fele-letelepedesi-kotvenyeken',
        sourceLabel: '444',
      },
      {
        title: 'NAV nyomozás – Rogán találmánya',
        description: 'A NAV nyomozása, amely Rogán Antal "találmányaként" elhíresült offshore-hálózat előzményeit vizsgálja, 2026-ban is aktívan folyik — a 444.hu szerint a nyomozás nem állt le, sőt kiszélesedett.',
        crimeTypes: ['Korrupció', 'Pénzmosás (gyanú)', 'Adócsalás (gyanú)'],
        sourceUrl: 'https://444.hu/2026/06/11/nem-allt-le-sot-aktivan-folyik-az-a-nav-os-nyomozas-ami-rogan-antal-talalmanyanak-elozmenyeit-is-vizsgalja',
        sourceLabel: '444',
      },
      {
        title: 'OFAC szankció',
        description: 'Az USA Pénzügyminisztériuma 2024-ben szankciókat vetett ki Rogánra, részletezve a korrupciót és a demokratikus intézmények szisztematikus aláásását. A szankció a letelepedési kötvény-hálózathoz is kapcsolódik.',
        crimeTypes: ['Korrupció', 'Demokratikus intézmények aláásása'],
        sourceUrl: 'https://24.hu/belfold/2025/01/07/rogan-antal-usa-szankcios-lista-magnyickij-torveny-korrupcio/',
        sourceLabel: '24.hu',
      },
      {
        title: 'NER propagandagépezet',
        description: 'Rogán Antal a Centrál Médiacsoport és a KESMA médiakonszolidáció mögötti politikai irányítóként koordinálta az állami hirdetési pénzek politikailag lojális médiumokhoz irányítását.',
        estimatedDamage: 'Több száz milliárd Ft reklámköltés',
        crimeTypes: ['Befolyással visszaélés', 'Közhatalommal visszaélés'],
        sourceUrl: 'https://444.hu/2026/06/14/101-ev-plakathiszteria-rogan-antal-es-balasy-gyula-magyarorszagan',
        sourceLabel: '444',
      },
      {
        title: 'Fiktív szerződések a III. kerületi önkormányzatnál',
        description: 'Rogán Antal 2006–2014 között Budapest III. kerületének (Óbuda–Békásmegyer) polgármestere volt. A K-Monitor adatbázisa 77 cikket dokumentál a kerületi önkormányzathoz köthető fiktív szerződések ügyéről, amelyek Rogán polgármesteri ciklusai idején köttetnek. Az ügyek közt találhatók túlszámlázott közbeszerzések, politikai alapon elosztott megbízások és átláthatatlan tenderek.',
        crimeTypes: ['Fiktív szerződések', 'Közbeszerzési visszaélés', 'Hivatali visszaélés'],
        sourceUrl: 'https://adatbazis.k-monitor.hu/adatbazis/cimkek/fiktiv-szerzodesek-a-iii-keruleti-onkormanyzatnal',
        sourceLabel: 'K-Monitor',
      },
    ],
  },
  {
    id: 'meszaros-lorinc',
    name: 'Mészáros Lőrinc',
    subtitle: 'Üzletember · Felcsút',
    description: 'Orbán Viktor gyerekkori barátja az elmúlt évtizedben az ország leggazdagabb emberévé vált — közbeszerzések, energetikai koncessziók és médiabirodalom révén. Vagyona 2010 előtt néhány száz millió, 2026-ra közel 900 milliárd forintra becsült.',
    detention: 'investig',
    detentionLabel: 'Vagyon­vizsgálat folyamatban',
    crimes: ['Közbeszerzési visszaélés', 'Jogtalan vagyonosodás', 'Bennfentes ügyletek'],
    amountLabel: 'Becsült vagyonnövekedés',
    amount: '~900 milliárd Ft',
    variant: 3, glasses: false, hair: 'bald',
    photoUrl: 'https://kep.cdn.indexvas.hu/1/0/1985/19857/198573/19857367_80ff5bffe0beda9d134343dec5c5d50d_wm.jpg',
    photoCredit: 'index.hu',
    videoId: 'rFpHB2w_O1o',
    videoChannel: 'Partizán',
    videoTitle: 'Kicsoda Mészáros Lőrinc?',
    videoSummary: 'Egy falusi gázszerelőből tíz év alatt Magyarország egyik leggazdagabb embere lett — Orbán barátjaként. A Partizán első részben tárja fel, hogyan épült fel a Mészáros-birodalom: ki fizette, ki nyitotta az ajtókat, és mi volt az ára.',
    newsTag: 'Mészáros Lőrinc',
    newsKeywords: ['mészáros lőrinc', 'mészáros'],
    personCases: [
      {
        title: 'Közbeszerzési birodalom',
        description: '2010 és 2026 között Mészáros cégei több ezer milliárdos állami és EU-finanszírozott közbeszerzési megrendelést nyertek el. Az Opus Global Nyrt. napjainkra az egyik legnagyobb magyar vállalat.',
        estimatedDamage: 'Több ezer milliárd Ft (közbeszerzések)',
        crimeTypes: ['Közbeszerzési visszaélés', 'Összeférhetetlenség'],
        sourceUrl: 'https://rtl.hu/hirado/2026/06/16/meszaros-lorinc-tovabbra-is-a-leggazdagabb-magyar-rekordot-dontott-a-hazai-milliardosok-vagyona',
        sourceLabel: 'RTL Híradó',
      },
      {
        title: 'KESMA médiakonszolidáció',
        description: 'Mészáros Lőrinc nevéhez fűződik a KESMA (Közép-európai Sajtó és Média Alapítvány) létrehozása, amely 500+ médiumot tömörít — így a politikailag lojális sajtó fenntartásának pénzügyi motorja.',
        crimeTypes: ['Médiapiaci torzítás', 'Politikai befolyásszerzés'],
        sourceUrl: 'https://telex.hu/tag/kesma',
        sourceLabel: 'Telex',
      },
      {
        title: 'Autópálya-koncesszió (35 évre)',
        description: 'A Mészáros Lőrinc és Szíjj László magántőkealapja által tulajdonolt MKIF (Magyar Koncessziós Infrastruktúra Fejlesztő Zrt.) 2023-ban 35 évre kapta meg 1237 km-nyi hazai gyorsforgalmi út üzemeltetési jogát. A 444.hu számítása szerint Mészárrosék 684 milliárd forint profitot zsebelhetnek be a futamidő alatt, az állam összes kifizetése elérheti a 15–17 ezer milliárd forintot — versenytárgyalás nélkül. A szerződést az aláírás után hat hónappal már módosítani kellett.',
        estimatedDamage: '684 milliárd Ft (becsült profit 35 év alatt)',
        crimeTypes: ['Versenytelen közbeszerzés', 'Közpénz elherdálása', 'Bennfentes ügyletek'],
        sourceUrl: 'https://telex.hu/gazdasag/2024/04/29/autopalya-koncesszio-meszaros-lorinc-szijj-laszlo-magantokealap-gyorsforgalmi-utak-nemzeti-koncesszios-iroda',
        sourceLabel: 'Telex',
      },
    ],
  },
  {
    id: 'tiborcz-istvan',
    name: 'Tiborcz István',
    subtitle: 'Orbán Viktor veje · BDPST Csoport alapítója',
    description: 'Tiborcz cégei 2011–2015 között közel 50 milliárd forintnyi EU-finanszírozott közvilágítási szerződést szereztek az Elios Innovatív Zrt.-n keresztül — az OLAF 16 milliárd Ft visszafizetését javasolta, magyar büntetőeljárás nem indult. A BDPST Csoporton keresztül azóta prémium ingatlanokból álló birodalmat épített ki: a cégcsoport becsült vagyona meghaladja a 188 milliárd forintot, 52 milliárd forint felhalmozott eredménytartalékkal. Orbán vejének politikai kapcsolatai vitathatatlan versenyelőnyt biztosítottak.',
    detention: 'investig',
    detentionLabel: 'OLAF vizsgálat · visszafizetés ajánlva',
    crimes: ['EU-forrás szabálytalan felhasználása', 'Bennfentes közbeszerzés', 'Jogtalan vagyonosodás'],
    amountLabel: 'Becsült vagyon (BDPST csoport)',
    amount: '188+ milliárd Ft',
    variant: 5, glasses: false, hair: 'short',
    photoUrl: 'https://bbj.hu/wp-content/uploads/2024/06/Tiborcz-Istvan-OK-1-1365x2048.jpg.webp',
    photoCredit: 'bbj.hu',
    videoId: '26q4cPw-W3A',
    videoChannel: '444.hu',
    videoTitle: 'Tiborcz a kamerák előtt',
    videoSummary: 'Orbán veje személyesen reagál az Elios-botrányra: karrierje szerinte már az uniós vizsgálat előtt elindult. De hogyan épített milliárdos vagyont egy huszonéves fiú néhány év alatt? A videóban Tiborcz saját szavaival mondja el — és olykor többet árul el, mint szeretne.',
    newsTag: 'Tiborcz',
    newsKeywords: ['tiborcz istván', 'tiborcz', 'elios'],
    personCases: [
      {
        title: 'Elios Innovatív Zrt. – közvilágítási botrány',
        description: 'Az Elios 2011–2015 között ~50 milliárdos EU-s közvilágítási tender-sorozatot nyert. Az OLAF 2017-ben 43,7 millió EUR szabálytalanságot tárt fel. Tiborcz 2015-ben eladta részesedését, de a vizsgálat alatt.',
        estimatedDamage: '43,7 millió EUR (OLAF javaslat)',
        crimeTypes: ['EU-forrás szabálytalan felhasználása', 'Bennfentes közbeszerzés'],
        sourceUrl: 'https://atlatszo.hu/kozpenz/2022/02/04/vegre-nyilvanos-az-elios-ugyrol-szolo-olaf-jelentes-bar-tiborcz-istvan-es-az-elios-nevet-kitakartak-benne/',
        sourceLabel: 'Átlátszó',
      },
      {
        title: 'BDPST Csoport – ingatlanbirodalom',
        description: 'Tiborcz a Párisi Udvar felújításával indult, azóta a BDPST Csoport az egyik legnagyobb prémium ingatlanfejlesztő Magyarországon. A cégcsoport 52 milliárd Ft eredménytartalékot halmozott fel; teljes becsült vagyona 188 milliárd Ft feletti. 2015–2026 között 11,4 milliárd Ft osztalékot vett ki. Az ingatlanok megszerzése és finanszírozása rendszeres sajtókritika tárgyát képezi.',
        estimatedDamage: '188+ milliárd Ft (becsült cégvagyon)',
        crimeTypes: ['Jogtalan vagyonosodás (gyanú)', 'Összeférhetetlenség'],
      },
      {
        title: 'Andezit Holding – magántőkealap',
        description: '2026 tavaszán az Andezit Holding és az ahhoz kötött magántőkealap-struktúra kapott sajtófigyelmet: állami hátterű pénzek és Tiborcz-érdekeltségek összefonódásáról számoltak be.',
        crimeTypes: ['Összeférhetetlenség (gyanú)', 'Közvagyon-közel üzleti érdekek'],
        sourceUrl: 'https://24.hu/fn/gazdasag/2026/04/01/tiborcz-istvan-andezit-magantokealap/',
        sourceLabel: '24.hu',
      },
      {
        title: 'Galyatetői hotel – közpénzmilliárdos felügyelet',
        description: 'Az Átlátszó 2026-ban tárta fel, hogy Tiborcz István és Orbán Ráhel is felügyeli a galyatetői szállodai beruházást, amelybe közpénzmilliárdok folynak.',
        crimeTypes: ['Összeférhetetlenség', 'Közvagyon-közel magánérdek'],
        sourceUrl: 'https://atlatszo.hu/orszagszerte/2026/06/15/galyatetoi-hotel-tiborcz-istvan-es-orban-rahel-is-felugyeli-a-kozpenzmilliardos-beruhazast/',
        sourceLabel: 'Átlátszó',
      },
      {
        title: 'Aligai kiemelt beruházás',
        description: 'A Club Aliga balatoni luxusszálló-projektet korábban részben Tiborcz István és Mészáros Lőrinc cégei érdekkörébe soroltak, majd NER-közeli fejlesztők vették át. A Kisfaludy 2030 Turisztikai Fejlesztési Közalapítvány közel 4 milliárd forint állami támogatást folyósított — négy év alatt a szálloda érdemi felújítás nélkül maradt, természetvédelmi területet is beépítve. A K-Monitor adatbázisában „kiemelt beruházásként" szerepel az ügy.',
        estimatedDamage: '~4 milliárd Ft (Kisfaludy 2030 állami támogatás)',
        crimeTypes: ['Közpénzek visszaélésszerű felhasználása', 'Bennfentes érdekeltség', 'Természetvédelmi terület sérelme'],
        sourceUrl: 'https://atlatszo.hu/orszagszerte/2026/06/08/negy-ev-alatt-kozel-negymilliard-forintos-allami-tamogatasbol-sem-ujult-meg-a-tiborcz-kozeli-hotel/',
        sourceLabel: 'Átlátszó',
      },
      {
        title: 'Zuglói ingatlanfejlesztés állami megvásárlása',
        description: '2023 júniusában az állam 244 milliárd forintért megvásárolta a Tiborcz István üzlettársához, Balázs Attilához köthető zuglói félkész irodaháztömböt. A szerződést az Országos Vagyonkezelő (MNV) nemzetbiztonsági okokra hivatkozva titkos minősítésűvé nyilvánította; a helyi önkormányzatot nem értesítette, holott elővásárlási joggal bírt. Hadházy Ákos pert nyert a részletek nyilvánosságra hozataláért.',
        estimatedDamage: '244 milliárd Ft',
        crimeTypes: ['Közvagyon elherdálása', 'Átláthatóság megsértése', 'Összeférhetetlenség'],
        sourceUrl: 'https://hvg.hu/gazdasag/20230609_244_milliard_forintert_veszi_meg_az_allam_a_zugloi_gigaberuhazast_Tiborcz_Istvan_uzlettarsatol',
        sourceLabel: 'HVG',
      },
      {
        title: 'Állami vagyon átadása magánalapítványoknak',
        description: 'A Fidesz-kormány 2021–2022-ben több száz milliárd forintnyi állami vagyont — kastélyokat, ingatlanokat, tőzsdei részesedéseket — adott át magán-kuratóriumok által irányított alapítványoknak (pl. egyetemi fenntartói alapítványok). Az átadások átláthatóság és parlamenti kontroll nélkül zajlottak; a K-Monitor adatbázisa 234 kapcsolódó cikket dokumentál.',
        crimeTypes: ['Közvagyon magánosítása', 'Átláthatóság megsértése', 'Parlamenti kontroll kijátszása'],
        sourceUrl: 'https://adatbazis.k-monitor.hu/adatbazis/cimkek/allami-vagyon-atadasa-maganalapitvanyoknak',
        sourceLabel: 'K-Monitor',
      },
    ],
  },
  {
    id: 'szijjarto-peter',
    name: 'Szíjjártó Péter',
    subtitle: 'Volt külügyminiszter',
    description: 'Miniszteri időszaka alatt több stratégiai szerződés körül érdekkonfliktust és átláthatósági problémákat azonosított a sajtó. Az azerbajdzsáni és orosz energetikai cégekhez fűződő üzleti kapcsolatai 2026-ban parlamenti vizsgálat tárgyát képezik.',
    detention: 'investig',
    detentionLabel: 'Vizsgálat folyamatban',
    crimes: ['Érdekkonfliktus', 'Átláthatóság megsértése', 'Közbeszerzési visszaélés'],
    amountLabel: 'Érintett szerződések értéke',
    amount: 'Több száz milliárd Ft',
    variant: 4, glasses: false, hair: 'short',
    photoUrl: 'https://symposium.org/wp-content/uploads/2023/12/Szijjarto_Peter_kep.jpg',
    photoCredit: 'symposium.org',
    videoId: '89pePZybTXo',
    videoChannel: 'Telex.hu',
    videoTitle: 'Önök milliárdosok?',
    videoSummary: 'Az újságíró egyenesen megkérdezi a külügyminisztert: milliárdosok-e? Szijjártó Péter válasza kitérő — de a vagyongyarapodás tényei egyértelműek. Ez a videó a 2024-es interjú legerősebb pillanatait mutatja be egy összeférhetetlenségi botrány árnyékában.',
    newsTag: 'Szíjjártó Péter',
    newsKeywords: ['szíjjártó péter', 'szíjjártó'],
    personCases: [
      {
        title: 'Azerbajdzsáni kapcsolatok',
        description: 'Szíjjártó miniszteri évei alatt kötött azerbajdzsáni energetikai és befektetési szerződések körül az ellenzék és a sajtó összeférhetetlenséget azonosított. A Vagif Aliyev-üggyel való kapcsolat vizsgálat alatt.',
        crimeTypes: ['Érdekkonfliktus', 'Közbeszerzési visszaélés'],
        sourceUrl: 'https://telex.hu/tag/szijjarto-peter',
        sourceLabel: 'Telex',
      },
      {
        title: 'Felesége cégének terjeszkedése',
        description: 'A HVG 2026-ban tárta fel, hogy Szíjjártó Péter felesége, Nagy Szilvia interior design cége a miniszteri évek alatt figyelemre méltó terjeszkedésen esett át — az összeférhetetlenség és a politikai protekció gyanúja sajtóvitát váltott ki.',
        crimeTypes: ['Összeférhetetlenség (gyanú)', 'Közvetlen érdekkonfliktus'],
        sourceUrl: 'https://hvg.hu/kkv/20260531_szijjarto-peter-nagy-szilvia-interior-design',
        sourceLabel: 'HVG',
      },
      {
        title: 'Diplomata-útlevél-osztogatás',
        description: 'Szíjjártó Péter külügyminiszteri irodájából 2010–2026 között mintegy 1322 diplomata-útlevelet ellenőrzött az új kormány — ezek közel 72%-át, 943-at visszavontak. Az útlevelek között sportolók (Rúzsa Magdi, Hajós András, Kálomista Gábor fia), NER-üzleti körök tagjai és külföldi állampolgárok is szerepeltek. Szakértők szerint a visszaélésszerű kiosztás komoly biztonsági kockázatot jelent.',
        crimeTypes: ['Hivatali visszaélés', 'Korrupció', 'Nemzeti biztonsági kockázat'],
        sourceUrl: 'https://444.hu/2026/06/05/ugy-osztogatta-a-diplomata-utleveleket-szijjarto-hivatala-mintha-kotelezo-lenne',
        sourceLabel: '444',
      },
      {
        title: 'Paks II. – hűtlen kezelés gyanúja',
        description: 'Az EU Bírósága 2025 szeptemberében megsemmisítette a Paks II. bővítéshez nyújtott állami támogatás jóváhagyását, megállapítva, hogy az versenyjogilag szabálytalan volt. Tordai Bence 2026 januárjában 80 milliárd forintos hűtlen kezelés gyanúja miatt feljelentést tett Szíjjártó Péter, Orbán Viktor és Nagy Márton ellen — arra hivatkozva, hogy az EU-s tiltás ellenére folytatták a beruházást.',
        estimatedDamage: '~80 milliárd Ft (Tordai feljelentés szerinti kár)',
        crimeTypes: ['Hűtlen kezelés (gyanú)', 'EU-szabályok megsértése', 'Közhatalommal visszaélés'],
        sourceUrl: 'https://nepszava.hu/3323893_paks-2-tordai-bence-feljelentes-hutlen-kezeles-gyanuja-orban-viktor-nagy-marton-szijjarto-peter',
        sourceLabel: 'Népszava',
      },
    ],
  },
  {
    id: 'takacs-peter',
    name: 'Takács Péter',
    subtitle: 'Volt egészségügyi államtitkár',
    description: 'A 2020-as lélegeztetőgép-vásárlás körül derült ki, hogy Takács sógora (Kőszegi Gábor) és Orbán főtanácsadójának fivére a Fourcardinal Zrt.-ből összesen milliárdos osztalékot vont ki. KEHI és NAV vizsgálata eljárás nélkül zárult.',
    detention: 'loose',
    detentionLabel: 'Nincs ismert eljárás',
    crimes: ['Érdekkonfliktus', 'Összeférhetetlenség'],
    amountLabel: 'Sógor által felvett osztalék',
    amount: '~8 milliárd Ft',
    variant: 1, glasses: true, hair: 'short',
    photoUrl: 'https://kep.cdn.indexvas.hu/1/0/6426/64266/642665/64266583_02646dcda0e9534845ab8f0750026dc5_wm.jpg',
    photoCredit: 'Index',
    videoId: 'DrHUAmHMZBM',
    videoChannel: 'Puzser Robert',
    videoTitle: 'Közpénztékozlás vagy pánikvasárlás?',
    videoSummary: '2020-ban Magyarország az EU-ban a legdrágábban vásárolta a kínai lélegeztetőgépeket — háromszoros áron, egy ismeretlen Fourcardinal Kft.-n keresztül. Ki döntött, ki keresett rajta, és miért nincs eddig senki felelősségre vonva? A 300 milliárdos ügylet mögé nézünk.',
    newsTag: 'Takács Péter',
    newsKeywords: ['takács péter', 'lélegeztetőgép', 'fourcardinal'],
    personCases: [
      {
        title: 'Lélegeztetőgép-botrány – rokoni kapcsolat',
        description: 'Takács Péter sógora (Kőszegi Gábor) a Silk Road Fund Holding Zrt.-n keresztül 8 milliárd Ft osztalékot vett fel a Fourcardinal Zrt.-ből — abból a cégből, amely a 300 milliárdos lélegeztetőgép-ügyletből hasznot húzott.',
        estimatedDamage: '~8 milliárd Ft (sógor osztaléka)',
        crimeTypes: ['Összeférhetetlenség', 'Érdekkonfliktus'],
        sourceUrl: 'https://444.hu/2026/06/08/a-fidesz-tovabbra-is-ott-tart-hogy-nem-vizsgalni-kellene-a-300-milliardos-lelegeztetogep-beszerzest-hanem-megkoszonni-azt',
        sourceLabel: '444',
      },
    ],
  },
  {
    id: 'matolcsy-gyorgy',
    name: 'Matolcsy György',
    subtitle: 'Volt MNB-elnök',
    description: 'Matolcsy György az MNB elnökeként 2013–2025 között 266 milliárd forintnyi közpénzt csatornázott át a jegybank alapítványain keresztül. Az ÁSZ (Állami Számvevőszék) kiszivárgott jelentés-tervezete súlyos vagyonvesztést és szabálytalanságokat tárt fel. Az ügyészség 2026-ban nyomozást indított hűtlen kezelés és más bűncselekmények gyanúja miatt.',
    detention: 'investig',
    detentionLabel: 'Nyomozás folyamatban',
    crimes: ['Hűtlen kezelés', 'Közpénzek hűtlen kezelése', 'Közhatalommal visszaélés'],
    amountLabel: 'ÁSZ által feltárt vagyonvesztés',
    amount: '266+ milliárd Ft',
    variant: 5, glasses: false, hair: 'wave',
    photoUrl: 'https://www.valaszonline.hu/wp-content/uploads/2025/04/ADSZZS202004160004-1536x864.jpg',
    photoCredit: 'Válasz Online',
    videoId: 'bgA0PTDFKlY',
    videoChannel: 'Telex.hu',
    videoTitle: 'Az MNB-botrány egy évvel később',
    videoSummary: 'Matolcsy György jegybankelnökként 266 milliárd forintot csatornázott alapítványokon keresztül magánkezekbe. Egy évvel a botrány kirobbanása után ez a videó megnézi: mi változott? A válasz rövid — szinte semmi. A főszereplők szabadon élnek, vagyon nem tért vissza.',
    newsTag: 'MNB',
    newsKeywords: ['matolcsy', 'mnb botrány', 'jegybank botrány', 'mnb-ügy'],
    personCases: [
      {
        title: 'MNB alapítványok – vagyonvesztés',
        description: 'Az MNB 266 milliárd forintot utalt át alapítványaiba (PSFN és társai), amelyek az ÁSZ kiszivárgott jelentés-tervezete szerint súlyos vagyonvesztést szenvedtek el. Az alapítványok céljai és a tényleges felhasználás között óriási szakadék tátong.',
        estimatedDamage: '266+ milliárd Ft',
        crimeTypes: ['Hűtlen kezelés', 'Közpénzek szabálytalan felhasználása'],
        sourceUrl: 'https://telex.hu/gazdasag/2026/06/11/matolcsy-gyorgy-170-millio-szabadsag-magyar-nemzeti-bank-vizsgalat',
        sourceLabel: 'Telex',
      },
      {
        title: 'ÁSZ vizsgálat és a kiszivárgott jelentés',
        description: 'Az Állami Számvevőszék jelentés-tervezete 2025-ben szivárgott ki — súlyos vagyonvesztést, átláthatatlansági problémákat és más szabálytalanságokat tárt fel Matolcsy György alapítványi rendszerénél. A hivatalos ÁSZ-jelentés végleges verziója ezután politikai nyomás alatt módosult.',
        crimeTypes: ['Közhatalommal visszaélés', 'Közpénzek ellenőrzésének akadályozása'],
        sourceUrl: 'https://444.hu/2025/03/19/tobb-buncselekmeny-gyanujaval-feljelentest-tett-a-szamvevoszek-az-mnb-alapitvanyok-gazdalkodasa-miatt',
        sourceLabel: '444',
      },
      {
        title: 'MNB székházfelújítás és ingatlanügyek',
        description: 'A Telex feltárta, hogy az MNB székházfelújítási projektjében a RAW Development érintett, amellyel szemben feljelentés is érkezett. Az MNB Ingatlan Kft. ügyletei számos átláthatósági kérdést vetnek fel.',
        crimeTypes: ['Közbeszerzési visszaélés', 'Átláthatóság megsértése'],
        sourceUrl: 'https://telex.hu/gazdasag/2025/10/20/mnb-szekhaz-felujitas-mnb-ingatlan-kft-feljelentes-raw-development',
        sourceLabel: 'Telex',
      },
      {
        title: 'Kecskeméti Neumann János Egyetem alapítvány',
        description: 'Az MNB-közelből finanszírozott alapítvány által felvásárolt kecskeméti campus és az "okosváros" projekt sorsa a Matolcsy-klán távozása után kérdésessé vált. A Telex belső dokumentumokra hivatkozva tárta fel, hogy az Optimából 170 millió forint tűnt el.',
        crimeTypes: ['Közpénzek szabálytalan felhasználása', 'Összeférhetetlenség'],
        sourceUrl: 'https://telex.hu/gazdasag/2026/04/30/mnb-ugy-kecskemet-njea-neumann-janos-egyetem-boross-ildiko-optimabol-tunt-el-a-penzt',
        sourceLabel: 'Telex',
      },
    ],
  },
  {
    id: 'lazar-janos',
    name: 'Lázár János',
    subtitle: 'Volt építési és közlekedési miniszter · volt polgármester, Miniszterelnökséget vezető miniszter',
    description: 'Középosztályból érkező politikusként vált az ország egyik legvagyonosabb képviselőjévé: 46 ingatlan, 3 luxusautó, 1+ milliárd forint nettó vagyon egy közpénzből élő politikus esetén. A batidai kastélyhoz vezető utat 2024-ben 3,3 milliárd forint közpénzből újíttatta fel — miközben mint építési és közlekedési miniszter dönthetett ilyen fejlesztésekről. Miniszterként egy tollvonással állíttatott le több száz MÁV-fejlesztést.',
    detention: 'investig',
    detentionLabel: 'Vagyonvizsgálat indokolt',
    crimes: ['Megmagyarázatlan vagyonosodás', 'Érdekkonfliktus', 'Közpénzek visszaélésszerű felhasználása'],
    amountLabel: 'Közpénzből felújított magánút',
    amount: 'min. 3,3 milliárd Ft',
    variant: 0, glasses: false, hair: 'short',
    photoUrl: 'https://ahang.hu/lopnak/wp-content/uploads/sites/3/2025/10/lazar-janos.jpg',
    photoCredit: 'ahang.hu',
    videoId: 'Zso0FRjX9cM',
    videoChannel: 'Kontroll',
    videoTitle: 'A batidai kastély rejtélye',
    videoSummary: 'Márki-Zay Péter a batidai Lázár-kastély előtt nyilatkozik — szembesítve a minisztert az ingatlan valódi értékével és finanszírozási kérdéseivel. Lázár János hogyan engedheti meg magának? A videó a közpénz és a magánvagyon határán jár.',
    newsTag: 'Lázár',
    newsKeywords: ['lázár jános', 'lázár', 'batida'],
    personCases: [
      {
        title: 'Batida kastély és a 3,3 milliárdos közút',
        description: 'Lázár János a batidai vadászháza körüli földek felvásárlására 181 millió forintot költött, és mára a kastély 40%-os tulajdonosa — korábban tagadta, hogy köze lenne az ingatlanhoz. 2024-ben az odavezető utat 3,3 milliárd forint közpénzből újíttatták fel, miközben Lázár mint építési és közlekedési miniszter felügyeli az ilyen beruházásokat.',
        estimatedDamage: '3,3 milliárd Ft (közút) · 181 millió Ft (földvásárlás)',
        crimeTypes: ['Érdekkonfliktus', 'Közpénzek visszaélésszerű felhasználása'],
        sourceUrl: 'https://444.hu/2025/04/14/kiveteles-alapossaggal-ujitottak-fel-a-lazar-janos-batidai-kastelyahoz-vezeto-utat',
        sourceLabel: '444',
      },
      {
        title: 'Megmagyarázatlan vagyonosodás',
        description: 'Lázár vagyonnyilatkozata szerint 46 ingatlan (3 lakóház, 35 szántó, 3 szőlő, 3 erdő, 1 töltés, 1 kivett mocsár), 3 luxusautó (Mini Cooper Cabrio, Land Rover Defender, Audi A6 Allroad), 200 millió Ft értékpapír, 90 millió Ft bankkövetelés, 30 millió Ft készpénz. A Népszava számítása szerint nettó vagyona meghaladja az 1 milliárd forintot.',
        estimatedDamage: '1+ milliárd Ft nettó vagyon',
        crimeTypes: ['Megmagyarázatlan vagyonosodás', 'Vagyonnyilatkozat-megkerülés gyanúja'],
        sourceUrl: 'https://nepszava.hu/3283192_lazar-janos-vagyona-milliardos',
        sourceLabel: 'Népszava',
      },
      {
        title: 'MÁV-fejlesztések leállítása',
        description: '2023-ban Lázár János egy döntéssel több száz MÁV fejlesztési projektet és részben karbantartási munkálatokat is felfüggesztett. 2024 júniusában ez közlekedési katasztrófához vezetett: a Budapest–Balaton vonalon a nyár első hétvégéin órákon át megbénult a vasúti forgalom.',
        crimeTypes: ['Közérdekű mulasztás', 'Közlekedésbiztonsági kockázat'],
        sourceUrl: 'https://nepszava.hu/3197594_lazar-janos-beruhazasok-felfuggesztes',
        sourceLabel: 'Népszava',
      },
      {
        title: 'Kastélyprogram – EU-pénzből felújított kastélyok magánkézbe adása',
        description: 'Lázár János mint építési és közlekedési miniszter 2023–2024-ben kastélyfelújítási programot indított, amelynek keretében közpénzből felújított (összesen ~22 milliárd forint) kastélyokat Fidesz-közeli magánszemélyeknek adott át. Az OLAF EU-s pénzek visszaélésszerű felhasználása miatt vizsgálatot indított; a program 2026 elején összeomlott, mindössze 2 kastély átadása után.',
        estimatedDamage: '~22 milliárd Ft',
        crimeTypes: ['EU-forrás visszaélésszerű felhasználása', 'Közvagyon elajándékozása', 'Hűtlen kezelés'],
        sourceUrl: 'https://adatbazis.k-monitor.hu/adatbazis/cimkek/lazar-janos/kastelyprogram',
        sourceLabel: 'K-Monitor',
      },
      {
        title: 'Mini-Dubaj Rákosrendezőn',
        description: 'Lázár János építési miniszterként 2024-ben 50,9 milliárd forintért adta el az Emírségekbe tartozó Eagle Hills befektetői csoportnak a rákosrendezői vasúti rendező pályaudvar területét, ahol 250–500 méteres felhőkarcolókat terveznek. A beruházás ellentmond Budapest 90 méteres épületmagassági korlátjának — Lázár egyedi miniszteri határozattal felülírta a szabályozást. Az ügyet a sajtó „Magyar Dubaj"-ként emlegeti.',
        estimatedDamage: '50,9 milliárd Ft (eladási ár) · ~5 milliárd EUR tervezett projekt',
        crimeTypes: ['Szabályozói visszaélés', 'Közvagyon elherdálása', 'Átláthatóság megsértése'],
        sourceUrl: 'https://telex.hu/gazdasag/2025/01/20/lazar-janos-mini-dubaj-rakosrendezo-500-meteres-felhokarcolo',
        sourceLabel: 'Telex',
      },
      {
        title: 'Állami vagyon átadása magánalapítványoknak – kuratóriumi nyereség',
        description: 'Lázár János a „Jövő Nemzedék Földje" Alapítvány kuratóriumi elnökeként a Fidesz-kormány 2021–2022-es állami vagyonátadási hullámából személyesen is profitált: az alapítványba kerülő állami cégekből (Nemzeti Ménesbirtok, ATEV, Concordia) összesen 4,5 milliárd forint osztalékot vett ki. Az átadások parlamenti felhatalmazás és nyilvános versenyeljárás nélkül zajlottak.',
        estimatedDamage: '4,5 milliárd Ft (Lázár közvetlen nyereménye)',
        crimeTypes: ['Közvagyon magánosítása', 'Összeférhetetlenség', 'Hűtlen kezelés'],
        sourceUrl: 'https://nyugatifeny.hu/2025/06/30/lazar-janos-hadhazy-akos-jovo-nemzedek-foldje-alapitvany/',
        sourceLabel: 'Nyugati Fény',
      },
      {
        title: 'Visszaélés a földpályázatoknál',
        description: '2015–2016-ban az állam privatizálta a Nemzeti Földalap termőterületeinek jelentős részét — a közvetlen értékesítési eljárást Lázár János a Miniszterelnöki Irodát vezető miniszterként felügyelte. Ángyán József volt agrárállamtitkár és az ellenzéki sajtó dokumentálta, hogy Fidesz-közeli hálózatok kaptak termőföldet, köztük nem gazdálkodók: ügyvédek, könyvelők, tanárok.',
        crimeTypes: ['Közbeszerzési visszaélés', 'Hivatali visszaélés', 'Közvagyon elherdálása'],
        sourceUrl: 'https://adatbazis.k-monitor.hu/adatbazis/cimkek/lazar-janos/visszaeles-a-foldpalyazatoknal',
        sourceLabel: 'K-Monitor',
      },
      {
        title: 'Egyetemi modellváltás',
        description: '2019–2022 között a Fidesz-kormány az állami egyetemek kb. 70%-át magán-alapítványi fenntartásba adta (Corvinus, BME, ELTE és mások). Az ingatlanátadásokban és a modellváltás jogi kereteinek kiépítésében Lázár János is szerepet kapott; az átadások átláthatóság és érdemi parlamenti vita nélkül zajlottak. Az Alkotmánybíróság egyes elemeket alkotmányellenesnek nyilvánított.',
        crimeTypes: ['Közvagyon magánosítása', 'Parlamenti kontroll kijátszása'],
        sourceUrl: 'https://adatbazis.k-monitor.hu/adatbazis/cimkek/lazar-janos/egyetemi-modellvaltas',
        sourceLabel: 'K-Monitor',
      },
      {
        title: 'Paks II. – építési felügyelet és titoktartás',
        description: 'Lázár János mint építési és közlekedési miniszter felügyeli a Paks II. bővítés megvalósítását. Az Orbán és Putyin által 2014-ben titkos záradékkal aláírt szerződés részletei 2045-ig titkosítottak. Az EU Bírósága 2025 szeptemberében megsemmisítette a beruházás állami támogatásának jóváhagyását, mégis folytatják az építkezést — amelyért Lázár miniszterként felelős.',
        estimatedDamage: '~3 ezer milliárd Ft (teljes projekt)',
        crimeTypes: ['EU-szabályok megsértése', 'Titoktartási visszaélés', 'Hűtlen kezelés (gyanú)'],
        sourceUrl: 'https://energiaklub.hu/hirek/a-paksi-beruhazas-korrupcios-kockazatai-3654',
        sourceLabel: 'Energiaklub',
      },
      {
        title: 'Kormány vs. Norvég Alap',
        description: 'Lázár János a Miniszterelnöki Irodát vezető miniszterként 2014-ben hatósági vizsgálatot indított az Ökotárs Alapítvány és más, EU-s Norvég Civil Alapból civil szervezeteknek osztó alapítványok ellen. A vizsgálat adóellenőrzéssel, irodaátkutatásokkal és számlazárolásokkal járt. Norvégia jogsértőnek nyilvánította a beavatkozást; a vizsgálat eredmény nélkül zárult.',
        crimeTypes: ['Civil szervezetek zaklatása', 'Politikai nyomásgyakorlás', 'Jogállamiság megsértése'],
        sourceUrl: 'https://adatbazis.k-monitor.hu/adatbazis/cimkek/lazar-janos/kormany-vs-norveg-alap',
        sourceLabel: 'K-Monitor',
      },
      {
        title: 'Trafik-mutyi',
        description: '2012-ben Lázár János terjesztette be azt a törvényt, amely megszüntette a szabad dohánykereskedelmet és bevezette a nemzeti dohánybolt-koncessziót. Az engedélyeket zömmel Fidesz-közeliek kapták; az elosztás szempontrendszere nem volt nyilvános. 2022-re a ~8000 koncessziós dohánybolt átlagos nyeresége elérte a 8,3 milliárd forintot.',
        crimeTypes: ['Monopólium-korrupció', 'Közbeszerzési visszaélés', 'Politikai privilégiumadás'],
        sourceUrl: 'https://hvg.hu/kkv/20230629_Lazar_Janos_continental_odbe_dohanykereskedelem_trafik_koncesszio',
        sourceLabel: 'HVG',
      },
      {
        title: 'Origo-ügy – szerkesztőfőnök kirúgása',
        description: '2014 májusában az Origo.hu feltárta, hogy Lázár János ~2 millió forintot költött egy 7 napos berlini kiküldetés során közpénzből szállodára. Lázár visszafizette az összeget; néhány nappal később az Origo szerkesztőjét, Sáling Gergőt kirúgták. A szerkesztőség tüntetéssel tiltakozott; a sajtó közvetlen összefüggést tételezett fel a két esemény között.',
        estimatedDamage: '~2 millió Ft (visszafizetett)',
        crimeTypes: ['Közpénz visszaélésszerű felhasználása', 'Sajtószabadság megsértése (gyanú)'],
        sourceUrl: 'https://adatbazis.k-monitor.hu/adatbazis/cimkek/lazar-janos/origo-ugy',
        sourceLabel: 'K-Monitor',
      },
      {
        title: 'Elios Zrt. – hódmezővásárhelyi közbeszerzések',
        description: 'Lázár János 2002–2014 között Hódmezővásárhely polgármestere volt. Az Elios Innovatív Zrt. — Tiborcz István cége — ebben az időszakban nyerte el a város összes közvilágítási tenderének 71%-át, 4,1 milliárd forint értékben. Az OLAF által vizsgált és 43,7 millió euró visszafizetését javasló EU-forrás-visszaélési ügy részben a hódmezővásárhelyi projektekre is kiterjed.',
        estimatedDamage: '4,1 milliárd Ft (helyi tenderek)',
        crimeTypes: ['Közbeszerzési visszaélés', 'Összeférhetetlenség', 'EU-forrás visszaélése'],
        sourceUrl: 'https://444.hu/2015/03/11/igy-kaptak-tiborczek-szabad-utat-a-milliardokhoz',
        sourceLabel: '444',
      },
    ],
  },
  {
    id: 'balasy-gyula',
    name: 'Balásy Gyula',
    subtitle: 'New Land Media alapítója',
    description: 'A New Land Media alapítója közel 700 milliárd forintnyi állami reklámköltést csatornázott át a Fidesz-közeli médiarendszeren keresztül. Balásy cégei közbeszerzés nélkül, háttéralkuk révén kapták a megrendeléseket. Az új kormány 2026-ban visszaköveti az állami pénzeket.',
    detention: 'investig',
    detentionLabel: 'Vagyonvizsgálat folyamatban',
    crimes: ['Közbeszerzési visszaélés', 'Állami pénzek hűtlen kezelése', 'Politikai összeférhetetlenség'],
    amountLabel: 'Érintett állami reklámköltés',
    amount: '~700 milliárd Ft',
    variant: 4, glasses: false, hair: 'wave',
    photoUrl: 'https://ahang.hu/lopnak/wp-content/uploads/sites/3/2025/09/balasy-gyula-1.jpg',
    photoCredit: 'ahang.hu',
    videoId: 'cslzmXaC51M',
    videoChannel: 'Kontroll',
    videoTitle: 'Balásy "önként" lemond',
    videoSummary: 'Balásy Gyula, a Fidesz kommunikációs főnöke bejelenti, hogy önként és ingyen átadja médiacégeit az államnak. De mi áll valójában e döntés mögött? A videó a NER médiamogulának hirtelen visszavonulását elemzi — és azt, hogy mennyire volt valóban önkéntes.',
    newsTag: 'Balásy Gyula',
    newsKeywords: ['balásy gyula', 'balásy', 'new land media'],
    personCases: [
      {
        title: 'Állami reklámbirodalom',
        description: 'Balásy Gyula New Land Media csoportja 2010–2026 között politikailag lojális médiumok felé irányította az állami reklámköltést, közbeszerzési verseny mellőzésével, közvetlen minisztériumi megrendelésekkel.',
        estimatedDamage: '~700 milliárd Ft (2010–2026)',
        crimeTypes: ['Közbeszerzési visszaélés', 'Hűtlen kezelés'],
        sourceUrl: 'https://telex.hu/gazdasag/2026/06/14/balasy-gyula-ceg-magantokealap-allam-felajanlas-vagyonleltar',
        sourceLabel: 'Telex',
      },
    ],
  },
  {
    id: 'semjen-zsolt',
    name: 'Semjén Zsolt',
    subtitle: 'Volt miniszterelnök-helyettes · KDNP elnök',
    description: 'A KDNP elnökeként és miniszterelnök-helyettesként az egyházi és vallási szektor milliárdos állami finanszírozásának kulcsszereplője. Nevéhez fűzódik az egyházi ingatlanok visszaadása és az aránytalanul magas egyházi normatívák rendszere, amelyek évente több tízmilliárd forint pluszt biztosítanak az egyházi fenntartóknak.',
    detention: 'loose',
    detentionLabel: 'Nincs ismert eljárás',
    crimes: ['Közpénzek aránytalanul elosztása', 'Egyházi privilégiumok jogtalan kiterjesztése'],
    amountLabel: 'Egyházi normatíva-különbözet',
    amount: 'Több száz milliárd Ft',
    variant: 1, glasses: true, hair: 'cap',
    photoUrl: 'https://temabaranya.hu/wp-content/uploads/2025/05/semjen_zsolt_vasarnap.hu_szennyes_krisztian_1000.jpg',
    photoCredit: 'témabaranya.hu',
    videoId: 'FlvGWxP5dzw',
    videoChannel: '444.hu',
    videoTitle: 'Semjén cáfol',
    videoSummary: 'Semjén Zsolt határozottan kijelenti: semmiféle bűnös viszonyhoz nem volt köze. A videó Semjén védekezését mutatja be — és közben sokat elárul arról, hogyan kommunikál a hatalom, amikor szorult helyzetbe kerül.',
    newsTag: 'Semjén',
    newsKeywords: ['semjén zsolt', 'semjén', 'zsolti bácsi', 'zsolt bácsi', 'kdnp'],
    personCases: [
      {
        title: 'Egyházi ingatlanvissza-adások',
        description: 'Semjén irányítása alatt az állam milliárd négyzetméternyi ingatlant adott vissza egyházaknak — sok esetben olyanokat is, amelyek sosem voltak egyházi tulajdonban, vagy amelyekre az egyháznak aktív igénye nem volt bizonyított.',
        estimatedDamage: 'Ismeretlen (ingatlanok piaci értéke)',
        crimeTypes: ['Közvagyon aránytalanul elosztása', 'Közhatalommal visszaélés'],
        sourceUrl: 'https://hvg.hu/itthon/20241114_Semjen-Zsolt-ingatlan-egyhaz-onkormanyzat-iskola',
        sourceLabel: 'HVG',
      },
      {
        title: 'Aránytalanul magas egyházi normatívák',
        description: 'Az egyházi iskolák állami normatívája 30–40%-kal magasabb az állami intézményeknél, miközben az egyházi szelekció torzítja az oktatási rendszert. A különbözet évente több tízmilliárd forint pluszt jelent az egyházi fenntartóknak.',
        estimatedDamage: 'Több tízmilliárd Ft/év',
        crimeTypes: ['Közpénzek aránytalanul elosztása'],
      },
      {
        title: 'Vadászatok és Farkas József – korrupciógyanú',
        description: 'A Transparency International és a K-Monitor 2018-ban büntetőfeljelentést tett Semjén Zsolt ellen. A szervezetek szerint Farkas József szállodás-vállalkozó mintegy 20–25 millió forint értékű luxusvadászatot fizetett Semjén számára (5 alkalommal Svédországban, 2 alkalommal Kanadában). Farkas cégei a szóban forgó időszakban 600 millió forint EU-s pályázati forrást nyertek, és 24 közbeszerzési szerződést kötöttek állami megrendelőkkel.',
        estimatedDamage: '~20–25 millió Ft értékű ajándék; 600 millió Ft EU-s pályázat (lehetséges kapcsolat)',
        crimeTypes: ['Vesztegetés fogadása (gyanú)', 'Összeférhetetlenség', 'Ajándék elfogadása (képviselőként tilos)'],
        sourceUrl: 'https://transparency.hu/hirek/ti-es-k-monitor-feljelentest-tesz-semjen-vadaszatai-ugyeben/',
        sourceLabel: 'Transparency International',
      },
    ],
  },
];
