export type MediaStatus = 'active' | 'closed' | 'fired-staff';
export type MediaGroup = 'print-kesma' | 'online' | 'tv-youtube' | 'radio';

export interface MediaOutletEntry {
  id: string;
  name: string;
  group: MediaGroup;
  owner: string;
  editorInChief?: string;
  description: string;
  status: MediaStatus;
  statusLabel: string;
  logoUrl?: string;
  logoCredit?: string;
  logoBgWhite?: boolean;
  logoScale?: number;
}

export const MEDIA_OUTLETS: MediaOutletEntry[] = [

  // ─── KESMA NYOMTATOTT ───────────────────────────────────────────────
  // Sor 1: Magyar Nemzet + 4 megszűnt + 2 kirúgott szerkesztőség
  {
    id: 'magyar-nemzet',
    name: 'Magyar Nemzet',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'A KESMA zászlóshajója, egykor a Fidesz kormány félhivatalos szócsöve. A lap 2018-ban megszűnt, majd újraindult KESMA-kiadásban.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'bors',
    name: 'Bors',
    group: 'print-kesma',
    owner: 'KESMA (Mediaworks)',
    description: 'Az ország egyik legnagyobb példányszámú bulvár napilapja. A Mediaworks 2025 végén leállította a nyomtatott kiadást.',
    status: 'closed',
    statusLabel: 'Megszűnt',
    logoUrl: 'https://image.blikk.hu/1/L9hktkpTURBXy8wYTBiZTBiMDllYzZjOGJjN2RmZDRjZTJhZDAwNmE4Zi5qcGeSlQMAzN7ND4jNCL6TCaY1MzNmYzQG/a-mediaworks-holnaptol-nem-adja-ki-bors-napilapot-foto-knap-zoltan',
    logoCredit: 'Blikk',
  },
  {
    id: '24-ora',
    name: '24 Óra',
    group: 'print-kesma',
    owner: 'KESMA (Mediaworks)',
    description: 'Komárom-Esztergom megyei napilap. 2026. július 1-jével megszűnt a nyomtatott kiadás.',
    status: 'closed',
    statusLabel: 'Megszűnt (2026. júl. 1.)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/210351524oralogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'nograd-hirlap',
    name: 'Nógrád Megyei Hírlap',
    group: 'print-kesma',
    owner: 'KESMA (Mediaworks)',
    description: 'Nógrád megye egyetlen nyomtatott napilapja. 2026. július 1-jével megszűnt a nyomtatott kiadás.',
    status: 'closed',
    statusLabel: 'Megszűnt (2026. júl. 1.)',
    logoUrl: 'https://www.ipolyinfo.com/wp-content/uploads/2026/06/Kepkivagas-11.jpg',
    logoCredit: 'ipolyinfo.hu',
    logoScale: 1.4,
  },
  {
    id: 'heves-hirlap',
    name: 'Heves Megyei Hírlap',
    group: 'print-kesma',
    owner: 'KESMA (Mediaworks)',
    description: 'Heves megye regionális napilapja. 2026. július 1-jével megszűnt a nyomtatott kiadás.',
    status: 'closed',
    statusLabel: 'Megszűnt (2026. júl. 1.)',
    logoUrl: 'https://media1.hu/wp-content/uploads/2021/11/heol.jpg',
    logoCredit: 'media1.hu',
  },
  {
    id: 'pesti-sracok-print',
    name: 'Pesti Srácok Magazin',
    group: 'print-kesma',
    owner: 'KESMA',
    description: '2026 tavaszán kirúgták az összes újságírójukat a nyomtatott magazintól — a lap technikailag létezik, de szerkesztőség nélkül maradt.',
    status: 'fired-staff',
    statusLabel: 'Összes újságíró kirúgva',
    logoUrl: 'https://hang.hu/data/generated/articles/159/1596/article-159607/PestiSracok_logo_focuspointscale_w1712_fx0_fy0.webp?key=MmQyMDc0Yjc0Y2IxYTc3YjkyZWQ2MjM2YzYzNjMxYWUwMGI5ZGQ2ODI3MGVmOTM2YjMzN2RhNTRmYjg3ZjAzYw==&v=1781634495',
    logoCredit: 'ahang.hu',
  },
  {
    id: 'vilaggazdasag-print',
    name: 'Világgazdaság (nyomtatott)',
    group: 'print-kesma',
    owner: 'KESMA (Mediaworks)',
    description: '2026 tavaszán kirúgták az összes újságírójukat a nyomtatott laptól — a napilap szerkesztőség nélkül maradt.',
    status: 'fired-staff',
    statusLabel: 'Összes újságíró kirúgva',
    logoUrl: '/images/media/vilaggazdasag.png',
    logoCredit: 'LinkedIn',
  },

  // Sor 2+: Aktív napilapok
  {
    id: 'mandiner',
    name: 'Mandiner',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Konzervatív politikai hetilap / magazin, a KESMA-csoport egyik közéleti kiadványa.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'delmagyarorszag',
    name: 'Délmagyarország',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Dél-magyarországi regionális lap (Szeged), a KESMA-birodalom egyik sarokköve.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'eszak-magyarorszag',
    name: 'Észak-Magyarország',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Miskolc és Borsod-Abaúj-Zemplén megye regionális napilapja.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'kisalfold',
    name: 'Kisalföld',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Győr-Moson-Sopron megye regionális napilapja.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'petofi-nepe',
    name: 'Petőfi Népe',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Bács-Kiskun megye napilapja, Kecskemét székhellyel.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'somogyi-hirlap',
    name: 'Somogyi Hírlap',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Kaposvár székhelyű regionális napilap, Somogy megye.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'zalai-hirlap',
    name: 'Zalai Hírlap',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Zala megye napilapja, Zalaegerszeg székhellyel.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'vas-nepe',
    name: 'Vas Népe',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Szombathely székhelyű, Vas megyei regionális lap.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'tolnai-nepujsag',
    name: 'Tolnai Népújság',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Tolna megye napilapja, Szekszárd székhellyel.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'fejer-hirlap',
    name: 'Fejér Megyei Hírlap',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Fejér megye regionális napilapja, Székesfehérvár székhellyel.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'hajdu-bihari',
    name: 'Hajdú-Bihari Napló',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Debrecen székhelyű, Hajdú-Bihar megye napilapja.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'bekes-hirlap',
    name: 'Békés Megyei Hírlap',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Békéscsaba székhelyű, Békés megye regionális napilapja.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'kelet-magyarorszag',
    name: 'Kelet-Magyarország',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Nyíregyháza székhelyű, Szabolcs-Szatmár-Bereg megye napilapja.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'uj-neplap',
    name: 'Új Néplap',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Jász-Nagykun-Szolnok megye napilapja, Szolnok székhellyel.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'uj-dunantuli-naplo',
    name: 'Új Dunántúli Napló',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Pécsi székhelyű regionális napilap, Baranya megye.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'naplo',
    name: 'Napló',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Veszprém megye regionális napilapja, Veszprém székhellyel.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'ripost',
    name: 'Ripost',
    group: 'print-kesma',
    owner: 'KESMA (Mediaworks)',
    description: 'Bulvár hetilap, a Mediaworks (KESMA) kiadásában.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: '/images/media/ripost.jpg',
    logoCredit: 'Facebook',
  },
  {
    id: 'metropol',
    name: 'Metropol',
    group: 'print-kesma',
    owner: 'KESMA (Mediaworks)',
    description: 'Ingyenes városi lap, terjesztve a tömegközlekedési csomópontokon.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2020/07/+otf/1920w/6+vL8nFyOS0QRoizK2TaBE5PVF9WRVJZX1NFQyVasADypyixtpeTc1wELnzAV8jN9LPpVckgrTQn3BZPDLMfxnO__5+U34yLGd3aNINXEKAPfHxBF2xH+sXh5Ldk=/7938949metrologo.png',
    logoCredit: 'Mediaworks',
  },
  {
    id: 'szabad-fold',
    name: 'Szabad Föld',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Vidéki gazdálkodóknak szóló hetilap, a KESMA-hálózat tagja.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'vasarnap-reggel',
    name: 'Vasárnap Reggel',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Hétvégi politikai hetilap, a KESMA-birodalom egyik közéleti kiadványa.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'fanny',
    name: 'Fanny',
    group: 'print-kesma',
    owner: 'KESMA',
    description: "KESMA-kiadású women's magazin, magyarországi terjesztésű hetilap.",
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'hot',
    name: 'Hot!',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Bulvár és celeb hetilap, a KESMA-kiadványok egyike.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'auto-motor',
    name: 'Autó-Motor',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Magyarország legrégebbi autós magazinja, KESMA-kiadásban megjelenő kétheti kiadvány.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'lakaskultura',
    name: 'Lakáskultúra',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Belsőépítészeti és otthon-dekorációs havilap, a KESMA magazin-portfóliójának tagja.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'videk-ize',
    name: 'Vidék Íze',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Gasztronómiai és vidéki életmód havilap, KESMA-kiadványok között.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },

  // ─── KESMA — ONLINE ─────────────────────────────────────────────────
  // Sor 1: megszűnt / kirúgott + aktív flagship portálok
  {
    id: 'metropol-online',
    name: 'Metropol.hu',
    group: 'online',
    owner: 'KESMA (Mediaworks)',
    description: 'A Metropol ingyenes városi lap online verziója. A weboldal megszűnt.',
    status: 'closed',
    statusLabel: 'Megszűnt',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2020/07/+otf/1920w/6+vL8nFyOS0QRoizK2TaBE5PVF9WRVJZX1NFQyVasADypyixtpeTc1wELnzAV8jN9LPpVckgrTQn3BZPDLMfxnO__5+U34yLGd3aNINXEKAPfHxBF2xH+sXh5Ldk=/7938949metrologo.png',
    logoCredit: 'Mediaworks',
  },
  {
    id: 'ripost-online',
    name: 'Ripost.hu',
    group: 'online',
    owner: 'KESMA (Mediaworks)',
    description: 'A Ripost bulvárlap online verziója. A weboldal megszűnt.',
    status: 'closed',
    statusLabel: 'Megszűnt',
    logoUrl: '/images/media/ripost.jpg',
    logoCredit: 'Facebook',
  },
  {
    id: 'pesti-sracok',
    name: 'Pesti Srácok',
    group: 'online',
    owner: 'KESMA',
    description: 'NER-közeli hírportál, az egyik legtöbbet hivatkozott Fidesz-propaganda felület. 2026 tavaszán kirúgták az összes újságírójukat — szerkesztőség nélkül maradt.',
    status: 'fired-staff',
    statusLabel: 'Összes újságíró kirúgva',
    logoUrl: 'https://hang.hu/data/generated/articles/159/1596/article-159607/PestiSracok_logo_focuspointscale_w1712_fx0_fy0.webp?key=MmQyMDc0Yjc0Y2IxYTc3YjkyZWQ2MjM2YzYzNjMxYWUwMGI5ZGQ2ODI3MGVmOTM2YjMzN2RhNTRmYjg3ZjAzYw==&v=1781634495',
    logoCredit: 'ahang.hu',
  },
  {
    id: 'vilaggazdasag',
    name: 'Világgazdaság (vg.hu)',
    group: 'online',
    owner: 'KESMA (Mediaworks)',
    description: 'Gazdasági napilap és hírportál. 2026 tavaszán kirúgták az összes újságírójukat — szerkesztőség nélkül maradt.',
    status: 'fired-staff',
    statusLabel: 'Összes újságíró kirúgva',
    logoUrl: '/images/media/vilaggazdasag.png',
    logoCredit: 'LinkedIn',
  },
  {
    id: 'origo',
    name: 'Origo.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Egykor az ország legnépszerűbb hírportálja — 2016 után a Fidesz-propaganda egyik leghatékonyabb eszközévé vált.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'magyarnemzet-online',
    name: 'Magyarnemzet.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'A Magyar Nemzet napilap online portálja, a KESMA digitális zászlóshajója.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'mandiner-online',
    name: 'Mandiner.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Konzervatív politikai hírportál és véleményoldal, a KESMA-hálózat meghatározó online lapja.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  // Sor 2+: tematikus és regionális portálok
  {
    id: 'hirvilag',
    name: 'Hírvilág.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'KESMA-hírportál, a regionális lapok anyagait aggregáló online felület.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'newsfeed',
    name: 'Newsfeed.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'KESMA-kézben lévő híraggregátor portál.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'life',
    name: 'Life.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'KESMA-tulajdonú életmód és szórakoztató portál, széles olvasótáborral.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'she',
    name: 'She.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Nőknek szóló KESMA-portál, divat és lifestyle tartalommal.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'mindmegette',
    name: 'Mindmegette.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Az egyik legnépszerűbb magyar gasztronómiai portál, a KESMA-csoport tagja.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'likebalaton',
    name: 'Likebalaton.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Balatoni turisztikai és életmód portál, KESMA-érdekeltségben.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'boon',
    name: 'Boon.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Borsodi Online — az Észak-Magyarország napilap digitális megfelelője.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'delmagyar',
    name: 'Delmagyar.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'A Délmagyarország napilap online portálja, Szeged és Csongrád-Csanád megye hírei.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'duol',
    name: 'Duol.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Dunántúli Online — az Új Dunántúli Napló digitális portálja, Pécs és Baranya megye.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'baon',
    name: 'Baon.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Bács-Kiskun Online — a Petőfi Népe napilap digitális megfelelője.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'sonline',
    name: 'Sonline.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Somogy Online — a Somogyi Hírlap napilap digitális portálja.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'teol',
    name: 'Teol.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Tolna Online — a Tolnai Népújság napilap digitális megfelelője.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'szoljon',
    name: 'Szoljon.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Szolnok és JNSz-megye hírportálja — az Új Néplap napilap online kiadása.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'vaol',
    name: 'Vaol.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Vas Online — a Vas Népe napilap digitális portálja.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'zaol',
    name: 'Zaol.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Zalai Online — a Zalai Hírlap napilap digitális portálja.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'haon',
    name: 'Haon.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Hajdú-Bihari Online — a Hajdú-Bihari Napló digitális megfelelője, Debrecen.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'beol',
    name: 'Beol.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Békés Online — a Békés Megyei Hírlap napilap digitális portálja.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'kemma',
    name: 'Kemma.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Komárom-Esztergom megye hírportálja, a 24 Óra napilap online kiadása.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'heol',
    name: 'Heol.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Heves Online — a Heves Megyei Hírlap napilap digitális megfelelője.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'nool',
    name: 'Nool.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Napló Online — a Napló (Veszprém megye) napilap digitális portálja.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'feol',
    name: 'Feol.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Fejér Online — a Fejér Megyei Hírlap napilap digitális megfelelője.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'kisalfold-online',
    name: 'Kisalfold.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'A Kisalföld napilap online portálja, Győr-Moson-Sopron megye hírportálja.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'szegedma',
    name: 'Szegedma.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Szegedi helyi hírportál, a KESMA regionális digitális jelenlétének része.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'mainap',
    name: 'Mainap.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'KESMA-kézben lévő hírportál.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },

  // ─── TELEVÍZIÓ / YOUTUBE ────────────────────────────────────────────
  {
    id: 'hir-tv',
    name: 'Hír TV',
    group: 'tv-youtube',
    owner: 'KESMA',
    description: 'Kereskedelmi hírtelevízió, 2018-ban KESMA-érdekeltségbe kerülve a NER médiabirodalom részévé vált.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'igazsag-oraja',
    name: 'Igazság Órája',
    group: 'tv-youtube',
    owner: 'Független NER-közeli',
    editorInChief: 'Németh Balázs',
    description: 'Németh Balázs NER-közelinek tartott YouTube csatornája. 2026-ban megszűnt.',
    status: 'closed',
    statusLabel: 'Megszűnt',
    logoUrl: 'https://kep.cdn.indexvas.hu/1/0/6567/65673/656733/65673351_20028254636b98b087d30d8e90ea0211_wm.jpg',
    logoCredit: 'Index',
  },
  {
    id: 'fair-right',
    name: 'Fair Right',
    group: 'tv-youtube',
    owner: 'Független NER-közeli',
    editorInChief: 'Varga Ádám · Vincze Emília',
    description: 'NER-közeli YouTube politikai műsor. 2026 tavaszán megszűnt.',
    status: 'closed',
    statusLabel: 'Megszűnt (2026 tavasz)',
    logoUrl: 'https://img.hvg.hu/Img/8133bb77-3fc3-490f-b374-cb198a0455cc/a256ab88-c24d-4137-bf3e-78883c3223c9.jpg',
    logoCredit: 'HVG',
  },
  {
    id: 'tenyek',
    name: 'Tények',
    group: 'tv-youtube',
    owner: 'TV2 (korábban NER-közeli)',
    description: 'A TV2 hírműsora, éveken át a NER-propaganda egyik fontos tévés felülete. 2026-ban megszűnt.',
    status: 'closed',
    statusLabel: 'Megszűnt',
    logoUrl: 'https://kep.cdn.indexvas.hu/1/0/6926/69267/692671/69267157_b3cc943be88e66fc48e9561a374096f5_wm.jpg',
    logoCredit: 'Index',
  },

  // ─── RÁDIÓ ──────────────────────────────────────────────────────────
  {
    id: 'hir-fm',
    name: 'Hír FM',
    group: 'radio',
    owner: 'KESMA',
    description: 'Kereskedelmi rádiócsoport, a KESMA hálózatának tagja. Politikailag Fidesz-közeli tartalmakat sugárzott.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'retro-radio',
    name: 'Retro Rádió',
    group: 'radio',
    owner: 'KESMA',
    description: 'KESMA-tulajdonú zenei rádió, a birodalom szórakoztató frekvenciája.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
];

export const MEDIA_GROUPS: { key: MediaGroup; label: string }[] = [
  { key: 'print-kesma', label: 'KESMA — Nyomtatott' },
  { key: 'online', label: 'KESMA — Online' },
  { key: 'tv-youtube', label: 'Televízió · YouTube' },
  { key: 'radio', label: 'KESMA — Rádió' },
];
