export type MediaStatus = 'active' | 'closed' | 'pending-closed' | 'fired-staff';
export type MediaGroup = 'print-kesma' | 'online' | 'tv-youtube' | 'radio';

export interface MediaOutletEntry {
  id: string;
  name: string;
  group: MediaGroup;
  owner: string;
  editorInChief?: string;
  description: string;
  status: MediaStatus;
  statusLabel: string;
  logoUrl?: string;
  logoCredit?: string;
  logoBgWhite?: boolean;
  logoScale?: number;
  sourceUrl?: string;
  sourceName?: string;
}

export const MEDIA_OUTLETS: MediaOutletEntry[] = [

  // ─── KESMA NYOMTATOTT ───────────────────────────────────────────────
  // Sor 1: Magyar Nemzet + 4 megszűnt + 2 kirúgott szerkesztőség
  {
    id: 'magyar-nemzet',
    name: 'Magyar Nemzet',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'A KESMA zászlóshajója, egykor a Fidesz kormány félhivatalos szócsöve. 2026 júniusában hetilappá alakult — a szerkesztőség felét kirúgták.',
    status: 'fired-staff',
    statusLabel: 'Szerkesztőség felét kirúgták (2026. jún.)',
    logoUrl: '/images/media/magyar-nemzet.svg',
    logoCredit: 'Wikimedia Commons',
    logoBgWhite: true,
  },
  {
    id: 'pesti-sracok-print',
    name: 'Pesti Srácok Magazin',
    group: 'print-kesma',
    owner: 'KESMA',
    description: '2026 tavaszán kirúgták az összes újságírójukat a nyomtatott magazintól — a lap technikailag létezik, de szerkesztőség nélkül maradt.',
    status: 'fired-staff',
    statusLabel: 'Összes újságíró kirúgva',
    logoUrl: 'https://hang.hu/data/generated/articles/159/1596/article-159607/PestiSracok_logo_focuspointscale_w1712_fx0_fy0.webp?key=MmQyMDc0Yjc0Y2IxYTc3YjkyZWQ2MjM2YzYzNjMxYWUwMGI5ZGQ2ODI3MGVmOTM2YjMzN2RhNTRmYjg3ZjAzYw==&v=1781634495',
    logoCredit: 'ahang.hu',
  },
  {
    id: 'vilaggazdasag-print',
    name: 'Világgazdaság (nyomtatott)',
    group: 'print-kesma',
    owner: 'KESMA (Mediaworks)',
    description: '2026 tavaszán kirúgták az összes újságírójukat a nyomtatott laptól — a napilap szerkesztőség nélkül maradt.',
    status: 'fired-staff',
    statusLabel: 'Összes újságíró kirúgva',
    logoUrl: '/images/media/vilaggazdasag.png',
    logoCredit: 'LinkedIn',
  },
  {
    id: 'bors',
    name: 'Bors',
    group: 'print-kesma',
    owner: 'KESMA (Mediaworks)',
    description: 'Az ország egyik legnagyobb példányszámú bulvár napilapja. A Mediaworks 2025 végén leállította a nyomtatott kiadást.',
    status: 'closed',
    statusLabel: 'Megszűnt',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2104058borslogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: '24-ora',
    name: '24 Óra',
    group: 'print-kesma',
    owner: 'KESMA (Mediaworks)',
    description: 'Komárom-Esztergom megyei napilap. 2026. július 1-jével megszűnt a nyomtatott kiadás.',
    status: 'closed',
    statusLabel: 'Megszűnt (2026. júl. 1.)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/210351524oralogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'nograd-hirlap',
    name: 'Nógrád Megyei Hírlap',
    group: 'print-kesma',
    owner: 'KESMA (Mediaworks)',
    description: 'Nógrád megye egyetlen nyomtatott napilapja. 2026. július 1-jével megszűnt a nyomtatott kiadás.',
    status: 'closed',
    statusLabel: 'Megszűnt (2026. júl. 1.)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2107522nogradlogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'heves-hirlap',
    name: 'Heves Megyei Hírlap',
    group: 'print-kesma',
    owner: 'KESMA (Mediaworks)',
    description: 'Heves megye regionális napilapja. 2026. július 1-jével megszűnt a nyomtatott kiadás.',
    status: 'closed',
    statusLabel: 'Megszűnt (2026. júl. 1.)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2105638heveshirlaplogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'gyor-plusz',
    name: 'Győr Plusz',
    group: 'print-kesma',
    owner: 'Fidesz-közeli (Borkai Zsolt köre)',
    description: 'Győri helyi hírportál, a Fidesz helyi holdudvarához köthető médium. 2026. május 16-án megszűnt — a rendszerváltás utáni sajtópiaci összeomlás egyik korai áldozata.',
    status: 'closed',
    statusLabel: 'Megszűnt (2026. máj. 16.)',
    logoUrl: 'https://www.gyorplusz.hu/wp-content/uploads/2024/10/gyp-logo2024.png',
    logoCredit: 'Győr Plusz',
    sourceUrl: 'https://24.hu/kultura/2026/05/16/gyor-plusz-fidesz-megszunes/',
    sourceName: '24.hu',
  },

  // Sor 2+: Aktív napilapok
  {
    id: 'mandiner',
    name: 'Mandiner',
    group: 'print-kesma',
    owner: 'KESMA (MCC)',
    description: '2026. június 24-én Kohán Mátyás főszerkesztő 60 munkatársat bocsátott el a Mandiner szerkesztőségéből. A lap MCC-tulajdonba kerülése után a leépítés a fideszes propagandagépezet belső átstrukturálásának részeként értékelhető.',
    status: 'fired-staff',
    statusLabel: 'Szerkesztőség kirúgva — 60 fő (2026. jún. 24.)',
    logoUrl: 'https://cdn.mandiner.hu/2023/06/_75HXrRgpF0z1155xmueeiWz-ZAs1GnX75poKNki_2M/fill/1347/758/no/1/aHR0cHM6Ly9jbXNjZG4uYXBwLmNvbnRlbnQucHJpdmF0ZS9jb250ZW50L2Y5ODQyYTYwNDY3YzQ4NjJhMTYyMDUyN2NhOWViOTAz.jpg',
    logoCredit: 'mandiner.hu',
    logoBgWhite: false,
    logoScale: 1,
  },
  {
    id: 'delmagyarorszag',
    name: 'Délmagyarország',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Dél-magyarországi regionális lap (Szeged), a KESMA-birodalom egyik sarokköve.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2104439delmagyarorszaglogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'eszak-magyarorszag',
    name: 'Észak-Magyarország',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Miskolc és Borsod-Abaúj-Zemplén megye regionális napilapja.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2104696eszakmologo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'kisalfold',
    name: 'Kisalföld',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Győr-Moson-Sopron megye regionális napilapja.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2106153kisalfoldlogo103.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'petofi-nepe',
    name: 'Petőfi Népe',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Bács-Kiskun megye napilapja, Kecskemét székhellyel.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2107643petofinepelogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'somogyi-hirlap',
    name: 'Somogyi Hírlap',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Kaposvár székhelyű regionális napilap, Somogy megye.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2107934somogylogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'zalai-hirlap',
    name: 'Zalai Hírlap',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Zala megye napilapja, Zalaegerszeg székhellyel.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2113619zalailogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'vas-nepe',
    name: 'Vas Népe',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Szombathely székhelyű, Vas megyei regionális lap.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2113345vasnepelogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'tolnai-nepujsag',
    name: 'Tolnai Népújság',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Tolna megye napilapja, Szekszárd székhellyel.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2112901tolnailogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'fejer-hirlap',
    name: 'Fejér Megyei Hírlap',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Fejér megye regionális napilapja, Székesfehérvár székhellyel.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2104919fejerhirlaplogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'hajdu-bihari',
    name: 'Hajdú-Bihari Napló',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Debrecen székhelyű, Hajdú-Bihar megye napilapja.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2105443hbnaplologo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'bekes-hirlap',
    name: 'Békés Megyei Hírlap',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Békéscsaba székhelyű, Békés megye regionális napilapja.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2103955bekeshirlaplogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'kelet-magyarorszag',
    name: 'Kelet-Magyarország',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Nyíregyháza székhelyű, Szabolcs-Szatmár-Bereg megye napilapja.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2106078keletmologo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'uj-neplap',
    name: 'Új Néplap',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Jász-Nagykun-Szolnok megye napilapja, Szolnok székhellyel.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2113192ujneplaplogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'uj-dunantuli-naplo',
    name: 'Új Dunántúli Napló',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Pécsi székhelyű regionális napilap, Baranya megye.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2113161dunantulilogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'naplo',
    name: 'Napló',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Veszprém megye regionális napilapja, Veszprém székhellyel.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2107078naplologo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'ripost',
    name: 'Ripost',
    group: 'print-kesma',
    owner: 'KESMA (Mediaworks)',
    description: 'Bulvár hetilap, a Mediaworks (KESMA) kiadásában.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: '/images/media/ripost.jpg',
    logoCredit: 'Facebook',
  },
  {
    id: 'metropol',
    name: 'Metropol',
    group: 'print-kesma',
    owner: 'KESMA (Mediaworks)',
    description: 'Ingyenes városi lap, terjesztve a tömegközlekedési csomópontokon.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2106946metropollogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'szabad-fold',
    name: 'Szabad Föld',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Vidéki gazdálkodóknak szóló hetilap, a KESMA-hálózat tagja.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2108419szabadfoldlogo68.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'vasarnap-reggel',
    name: 'Vasárnap Reggel',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Hétvégi politikai hetilap, a KESMA-birodalom egyik közéleti kiadványa.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/21180310vasarnapreggellogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'fanny',
    name: 'Fanny',
    group: 'print-kesma',
    owner: 'KESMA',
    description: "KESMA-kiadású women's magazin, magyarországi terjesztésű hetilap.",
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2104860fannylogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'hot',
    name: 'Hot!',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Bulvár és celeb hetilap, a KESMA-kiadványok egyike.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2105810hotlogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'auto-motor',
    name: 'Autó-Motor',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Magyarország legrégebbi autós magazinja, KESMA-kiadásban megjelenő kétheti kiadvány.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2103742automotorlogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'lakaskultura',
    name: 'Lakáskultúra',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Belsőépítészeti és otthon-dekorációs havilap, a KESMA magazin-portfóliójának tagja.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2106358lakulogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'videk-ize',
    name: 'Vidék Íze',
    group: 'print-kesma',
    owner: 'KESMA',
    description: 'Gasztronómiai és vidéki életmód havilap, KESMA-kiadványok között.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2113471videkizelogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },

  // ─── KESMA — ONLINE ─────────────────────────────────────────────────
  {
    id: 'metropol-online',
    name: 'Metropol.hu',
    group: 'online',
    owner: 'KESMA (Mediaworks)',
    description: 'A Metropol ingyenes városi lap online verziója. A weboldal megszűnt.',
    status: 'closed',
    statusLabel: 'Megszűnt',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2106946metropollogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'ripost-online',
    name: 'Ripost.hu',
    group: 'online',
    owner: 'KESMA (Mediaworks)',
    description: 'A Ripost bulvárlap online verziója. A weboldal megszűnt.',
    status: 'closed',
    statusLabel: 'Megszűnt',
    logoUrl: '/images/media/ripost.jpg',
    logoCredit: 'Facebook',
  },
  {
    id: 'origo',
    name: 'Origo.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Egykor az ország legnépszerűbb hírportálja, 2016 után a Fidesz-propaganda egyik leghatékonyabb eszköze. 2026 júniusában az alkalmazottak 75%-át kirúgták egyetlen nap alatt.',
    status: 'fired-staff',
    statusLabel: '75% kirúgva (2026. jún. 17.)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2107588origologo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'magyarnemzet-online',
    name: 'Magyarnemzet.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'A Magyar Nemzet napilap online portálja, a KESMA digitális zászlóshajója. 2026 júniusában a nyomtatott szerkesztőség felét kirúgták a hetilappá alakulás miatt.',
    status: 'fired-staff',
    statusLabel: 'Szerkesztőség felét kirúgták (2026. jún.)',
    logoUrl: '/images/media/magyar-nemzet.svg',
    logoCredit: 'Wikimedia Commons',
    logoBgWhite: true,
  },
  {
    id: 'pesti-sracok',
    name: 'Pesti Srácok',
    group: 'online',
    owner: 'KESMA',
    description: 'NER-közeli hírportál, az egyik legtöbbet hivatkozott Fidesz-propaganda felület. 2026 tavaszán kirúgták az összes újságírójukat — szerkesztőség nélkül maradt.',
    status: 'fired-staff',
    statusLabel: 'Összes újságíró kirúgva',
    logoUrl: 'https://hang.hu/data/generated/articles/159/1596/article-159607/PestiSracok_logo_focuspointscale_w1712_fx0_fy0.webp?key=MmQyMDc0Yjc0Y2IxYTc3YjkyZWQ2MjM2YzYzNjMxYWUwMGI5ZGQ2ODI3MGVmOTM2YjMzN2RhNTRmYjg3ZjAzYw==&v=1781634495',
    logoCredit: 'ahang.hu',
  },
  {
    id: 'vilaggazdasag',
    name: 'Világgazdaság (vg.hu)',
    group: 'online',
    owner: 'KESMA (Mediaworks)',
    description: 'Gazdasági napilap és hírportál. 2026 tavaszán kirúgták az összes újságírójukat — szerkesztőség nélkül maradt.',
    status: 'fired-staff',
    statusLabel: 'Összes újságíró kirúgva',
    logoUrl: '/images/media/vilaggazdasag.png',
    logoCredit: 'LinkedIn',
  },
  {
    id: 'mandiner-online',
    name: 'Mandiner.hu',
    group: 'online',
    owner: 'KESMA (MCC)',
    description: '2026. június 24-én 60 munkatársat küldtek el a Mandiner online szerkesztőségéből is. Kohán Mátyás főszerkesztő az MCC égisze alatt végrehajtott tömeges leépítés a propagandamédia átszervezésének része.',
    status: 'fired-staff',
    statusLabel: 'Szerkesztőség kirúgva — 60 fő (2026. jún. 24.)',
    logoUrl: 'https://cdn.mandiner.hu/2023/06/_75HXrRgpF0z1155xmueeiWz-ZAs1GnX75poKNki_2M/fill/1347/758/no/1/aHR0cHM6Ly9jbXNjZG4uYXBwLmNvbnRlbnQucHJpdmF0ZS9jb250ZW50L2Y5ODQyYTYwNDY3YzQ4NjJhMTYyMDUyN2NhOWViOTAz.jpg',
    logoCredit: 'mandiner.hu',
    logoBgWhite: false,
    logoScale: 1,
  },
  // Sor 2+: tematikus és regionális portálok
  {
    id: 'hirvilag',
    name: 'Hírvilág.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'KESMA-hírportál, a regionális lapok anyagait aggregáló online felület.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
  {
    id: 'newsfeed',
    name: 'Newsfeed.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'KESMA-kézben lévő híraggregátor portál.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2107493newsfeedlogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'life',
    name: 'Life.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'KESMA-tulajdonú életmód és szórakoztató portál, széles olvasótáborral.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2106319lifelogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'she',
    name: 'She.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Nőknek szóló KESMA-portál, divat és lifestyle tartalommal.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2107906shelogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'mindmegette',
    name: 'Mindmegette.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Az egyik legnépszerűbb magyar gasztronómiai portál, a KESMA-csoport tagja.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2024/10/7941761mindmegettelogo2rgb.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'likebalaton',
    name: 'Likebalaton.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Balatoni turisztikai és életmód portál, KESMA-érdekeltségben.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2106458lblogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'boon',
    name: 'Boon.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Borsodi Online — az Észak-Magyarország napilap digitális megfelelője.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2104025boonlogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'delmagyar',
    name: 'Delmagyar.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'A Délmagyarország napilap online portálja, Szeged és Csongrád-Csanád megye hírei.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2104416delmagyarlogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'duol',
    name: 'Duol.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Dunántúli Online — az Új Dunántúli Napló digitális portálja, Pécs és Baranya megye.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2104623duollogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'baon',
    name: 'Baon.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Bács-Kiskun Online — a Petőfi Népe napilap digitális megfelelője.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2103921baonlogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'sonline',
    name: 'Sonline.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Somogy Online — a Somogyi Hírlap napilap digitális portálja.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2107968sonlinelogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'teol',
    name: 'Teol.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Tolna Online — a Tolnai Népújság napilap digitális megfelelője.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2112848teollogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'szoljon',
    name: 'Szoljon.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Szolnok és JNSz-megye hírportálja — az Új Néplap napilap online kiadása.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2108547szoljonlogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'vaol',
    name: 'Vaol.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Vas Online — a Vas Népe napilap digitális portálja.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2113312vaollogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'zaol',
    name: 'Zaol.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Zalai Online — a Zalai Hírlap napilap digitális portálja.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2113645zaollogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'haon',
    name: 'Haon.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Hajdú-Bihari Online — a Hajdú-Bihari Napló digitális megfelelője, Debrecen.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2105482haonlogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'beol',
    name: 'Beol.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Békés Online — a Békés Megyei Hírlap napilap digitális portálja.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2103994beollogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'kemma',
    name: 'Kemma.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Komárom-Esztergom megye hírportálja, a 24 Óra napilap online kiadása.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2106101kemmalogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'heol',
    name: 'Heol.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Heves Online — a Heves Megyei Hírlap napilap digitális megfelelője.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2105510heollogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'nool',
    name: 'Nool.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Napló Online — a Napló (Veszprém megye) napilap digitális portálja.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2107547noollogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'feol',
    name: 'Feol.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Fejér Online — a Fejér Megyei Hírlap napilap digitális megfelelője.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2104951feollogo.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'kisalfold-online',
    name: 'Kisalfold.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'A Kisalföld napilap online portálja, Győr-Moson-Sopron megye hírportálja.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2021/04/2106193kisalfoldlogo43.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'szegedma',
    name: 'Szegedma.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'Szegedi helyi hírportál, a KESMA regionális digitális jelenlétének része.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2025/11/3558528szegedma.png',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'mainap',
    name: 'Mainap.hu',
    group: 'online',
    owner: 'KESMA',
    description: 'KESMA-kézben lévő hírportál.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },

  // ─── TELEVÍZIÓ / YOUTUBE ────────────────────────────────────────────
  {
    id: 'megafon',
    name: 'Megafon',
    group: 'tv-youtube',
    owner: 'NER-közeli (Habony Árpád köre)',
    description: 'A NER egyik legaktívabb propagandacsatornája YouTube-on és online. A Media1 értesülése szerint 2026. június 26-án az utolsó alkalmazott is távozik — a megszűnés egyelőre nem 100%-ban megerősített hír.',
    status: 'pending-closed',
    statusLabel: 'Megszűnt* (2026. jún. 26.)',
    sourceUrl: 'https://media1.hu/2026/06/25/veget-erhet-a-megafon-mukodese-penteken-az-utolso-alkalmazott-is-tavozik/',
    sourceName: 'Media1',
    logoUrl: '/images/media/megafon.webp',
    logoCredit: 'Megafon',
  },
  {
    id: 'tenyek',
    name: 'Tények',
    group: 'tv-youtube',
    owner: 'TV2 (korábban NER-közeli)',
    description: 'A TV2 hírműsora, éveken át a NER-propaganda egyik fontos tévés felülete. 2026-ban megszűnt.',
    status: 'closed',
    statusLabel: 'Megszűnt',
    logoUrl: 'https://kep.cdn.indexvas.hu/1/0/6926/69267/692671/69267157_b3cc943be88e66fc48e9561a374096f5_wm.jpg',
    logoCredit: 'Index',
  },
  {
    id: 'vadhajtasok',
    name: 'Vadhajtások.hu',
    group: 'tv-youtube',
    owner: 'Bede Zsolt (független NER-közeli)',
    editorInChief: 'Bede Zsolt',
    description: 'Orbán Viktor „igeforrása" — szélsőjobboldali propagandaoldal. 2026. június 17-én Bede Zsoltnál házkutatást tartottak (Perintfalvi Rita és Pottyondy Edina feljelentései nyomán), adathordozóit lefoglalták. Az oldal ezután elérhetetlen lett.',
    status: 'closed',
    statusLabel: 'Megszűnt (2026. jún. — házkutatás után)',
    logoUrl: 'https://vadhajtasok.wordpress.com/wp-content/uploads/2018/01/cropped-26166222_765724486952641_7768550140202283466_n.jpg',
    logoCredit: 'Vadhajtások',
  },
  {
    id: 'igazsag-oraja',
    name: 'Igazság Órája',
    group: 'tv-youtube',
    owner: 'Független NER-közeli',
    editorInChief: 'Németh Balázs',
    description: 'Németh Balázs NER-közelinek tartott YouTube csatornája. 2026-ban megszűnt.',
    status: 'closed',
    statusLabel: 'Megszűnt',
    logoUrl: 'https://kep.cdn.indexvas.hu/1/0/6567/65673/656733/65673351_20028254636b98b087d30d8e90ea0211_wm.jpg',
    logoCredit: 'Index',
  },
  {
    id: 'fair-right',
    name: 'Fair Right',
    group: 'tv-youtube',
    owner: 'Független NER-közeli',
    editorInChief: 'Varga Ádám · Vincze Emília',
    description: 'NER-közeli YouTube politikai műsor. 2026 tavaszán megszűnt.',
    status: 'closed',
    statusLabel: 'Megszűnt (2026 tavasz)',
    logoUrl: 'https://img.hvg.hu/Img/8133bb77-3fc3-490f-b374-cb198a0455cc/a256ab88-c24d-4137-bf3e-78883c3223c9.jpg',
    logoCredit: 'HVG',
  },
  {
    id: 'tv2',
    name: 'TV2',
    group: 'tv-youtube',
    owner: 'TV2 Csoport (Mészáros Lőrinc köre)',
    description: 'Magyarország egyik legnagyobb kereskedelmi televíziója, a NER-rendszerben a Fidesz-propaganda egyik fő tévés felülete volt. 2026-ban a politikai átállás után szerkesztőségi változásokat hajtott végre.',
    status: 'active',
    statusLabel: 'Aktív',
    logoUrl: '/images/media/tv2.jpg',
    logoCredit: 'TV2 Csoport',
    logoBgWhite: true,
  },
  {
    id: 'hir-tv',
    name: 'Hír TV',
    group: 'tv-youtube',
    owner: 'KESMA',
    description: 'Kereskedelmi hírtelevízió, 2018-ban KESMA-érdekeltségbe kerülve a NER médiabirodalom részévé vált.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: '/images/media/hir-tv.svg',
    logoCredit: 'Wikimedia Commons',
    logoBgWhite: true,
  },

  // ─── RÁDIÓ ──────────────────────────────────────────────────────────
  {
    id: 'hir-fm',
    name: 'Hír FM',
    group: 'radio',
    owner: 'KESMA',
    description: 'Kereskedelmi rádiócsoport, a KESMA hálózatának tagja. Politikailag Fidesz-közeli tartalmakat sugárzott.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
    logoUrl: 'https://mediaworks.hu/wp-content/uploads/2023/06/6820518hirfmm-e1686894581476.jpg',
    logoCredit: 'Mediaworks',
    logoBgWhite: true,
  },
  {
    id: 'retro-radio',
    name: 'Retro Rádió',
    group: 'radio',
    owner: 'KESMA',
    description: 'KESMA-tulajdonú zenei rádió, a birodalom szórakoztató frekvenciája.',
    status: 'active',
    statusLabel: 'Aktív (NER-közeli)',
  },
];

export const MEDIA_GROUPS: { key: MediaGroup; label: string }[] = [
  { key: 'print-kesma', label: 'KESMA — Nyomtatott' },
  { key: 'online', label: 'KESMA — Online' },
  { key: 'tv-youtube', label: 'Televízió · YouTube · Egyéb' },
  { key: 'radio', label: 'KESMA — Rádió' },
];
